[package]
name = "ansi-parser-extended"
version = "0.1.0"
edition = "2021"


[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-parser = "0.9.0"
demonstrate = "0.4.5"
bitflags = "2.5.0"
heapless = "0.6.1"
test-case = "3.3.1"
clap = { version = "4", features = ["derive"] }
pretty_assertions = "1.4.0"
serde_json = "1.0.117"
serde = { version = "1.0.201", features = ["derive"] }
tempfile = "3.10.1"
get_chunk = "1.2.1"

async-stream = "0.3.5"
futures-core = "0.3.30"
futures-util = "0.3.30"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "fs", "io-util"] }
tokio-stream = "0.1.15"
futures = "0.3.30"
nom = "7.1.3"
sonic-rs = "0.3.5"
atoi = "2.0.0"
const_typed_builder = "0.3.0"
