[package]
name = "ansi-parser-extended"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-parser = "0.9.0"
demonstrate = "0.4.5"
bitflags = "2.5.0"
heapless = "0.6.1"
test-case = "3.3.1"
clap = { version = "4", features = ["derive"] }
pretty_assertions = "1.4.0"
serde_json = "1.0.117"
serde = { version = "1.0.201", features = ["derive"] }
tempfile = "3.10.1"
